FROM openjdk:17-jdk
WORKDIR /app
COPY target/springboot_backend-0.0.1-SNAPSHOT.jar  /app/springboot_backend-0.0.1-SNAPSHOT.jar
EXPOSE 8080
CMD ["java","-jar","springboot_backend-0.0.1-SNAPSHOT.jar"]